GET https://localhost:5001/api/Trips/GetTrips
###
GET https://localhost:5001/api/Trips/SingleTrip/22
###
POST https://localhost:5001/api/Trips/AddTrip
Content-Type: application/json; charset=utf-8

{
    "id": 22,
    "name": "Venturaaa, CA, USA",
    "description": "Ventura is a city located on the central coast of California...",
    "dateStarted": "2023-09-19T00:00:00",
    "dateCompleted": "2023-09-19T23:00:00"
}
###
PUT https://localhost:5001/api/Trips/UpdateTrip/22
Content-Type: application/json; charset=utf-8

{
    "id": 22,
    "name": "Venturaaa updated, CA, USA",
    "description": "Ventura is a city located on the central coast of California...",
    "dateStarted": "2023-09-19T00:00:00",
    "dateCompleted": "2023-09-19T23:00:00"
}
###
DELETE https://localhost:5001/api/Trips/DeleteTrip/22